apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  labels:
    app: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simeple-app
  template:
    metadata:
      labels:
        app: simeple-app
    spec:
      containers:
      - name: simeple-app
        image: yumyum160/edn:ebfe8f8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eds
  namespace: prod
spec:
  selector:
    matchLabels:
      app: eds
  replicas: 1
  template:
    metadata:
      labels:
        app: eds
    spec:
      containers:
      - image: yumyum160/eds:latest
        name: eds
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eds
  namespace: prod
  annotations:
    external-dns.alpha.kubernetes.io/hostname: www.wow-pres-insa-isitr.com
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  selector:
    app: eds
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wow
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: www.wow-pres-insa-isitr.com
      http:
        paths:
          - path: /eds(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: eds
                port:
                  number: 80