apiVersion: apps/v1
kind: Deployment
metadata:
  name: edn
  labels:
    app: edn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edn
  template:
    metadata:
      labels:
        app: edn
    spec:
      containers:
      - name: edn
        image: yumyum160/edn:44f4d12
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: edn
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  selector:
    app: edn
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wow
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: www.wow-pres-insa-isitr.com
      http:
        paths:
          - path: /edn(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: edn
                port:
                  number: 80