apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  labels:
    app: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simeple-app
  template:
    metadata:
      labels:
        app: simeple-app
    spec:
      containers:
      - name: simeple-app
        image: yumyum160/edn:lastest
        ports:
        - containerPort: 80